Add Pin Map Client to the Measurement Server project
ni/measurement-plugin-labview pull request #576
Opened 2024-08-23 05:53 UTC by MounikaBattu17

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md). _(Required)_
- [ ]  Automatically post PR comments with images for G code changes? _(Recommended for small changes)_

### What does this Pull Request accomplish?
As a part of Measurement Client work, we are adding Pin Map Client to support Pin Map related APIs.
Implements [User Story 2738656](https://dev.azure.com/ni/DevCentral/_workitems/edit/2738656): As a user, I want to have an option to register the pin map and support pin-based measurements

### Why should this Pull Request be merged?
- Added new library `NI Pin Map V1 Client`
- Added below wrappers VIs to the library                                                    
    __________________
   - Create Client.vi                      
   - ReCreate Client.vi   
   - Destroy Client.vi                      
   - Pin Map Client FGV.vi        
   - Update Pin Map from XML.vi
   These files are moved from tests to this library and the access scope is set to `community`.
   _______________________
   - Register Pin Map.vi - This VI will register the given pin map with the pin map service. Created Measurement Client will use this VI, so we are planning to expose this VI in the functions palette. Hence the access scope is `public`.
  
- Added a helper VI `Read Pin Map File Contents. vi ` which will return the pin map file contents as a string.
- Added automated tests

### What testing has been done?
Added automated tests

2024-08-23 06:01 UTC, MounikaBattu17 commented on Source/Tests/Tests.Runtime/Measurement Server/Helpers/Kill Pin Map Service.vi
**Diff images:**
![diagram-A-before-0](https://github.com/user-attachments/assets/17cb6c2c-5879-4914-94cb-828c54660b25)
![diagram-B-after-0](https://github.com/user-attachments/assets/f6e243d7-02bf-4814-90da-d57af3ad21de)

2024-08-23 06:05 UTC, MounikaBattu17 commented on Source/Tests/Tests.Runtime/Measurement Server/Helpers/Register Pin Map.vi
**Diff images:**
![diagram-A-before-0](https://github.com/user-attachments/assets/f286d276-9f71-4225-bdc8-fdc540a9e493)
![diagram-B-after-0](https://github.com/user-attachments/assets/bb774f4d-d286-4be9-a33e-c3e0adc1d7c9)

2024-08-23 13:30 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
Currently, this VI is placed directly under NI Pin Map V1 folder. But this placement might change when exposing this VI in the palette in upcoming PRs.

2024-08-23 16:00 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Helpers/Kill Pin Map Service.vi
`Kill Session Management Service.vi` is still using the old service name as well. Can you please fix that while you are here?

2024-08-23 16:13 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Pin Map/test_UpdatePinMapfromXML_StopPinMapService_UpdatePinMapfromXMLWorksWithoutError.vi
I think a better name would be `test_ExistingClientConnection_StopPinMapService_UpdatePinMapFromXMLWorksWithoutError.vi`.

2024-08-23 16:28 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Pin Map/test_RegisterPinMap_RegisterPinMapFile_PinMapRegistered.vi
You should either:
- Use the FGV to get the existing client ID and then not call Destroy Client on the FGV (that's the whole point of the pool is to reuse the connection).
- Use the grpc-labview VI for closing the client session. You can either use the VI from the palette or the one that is code generated with the pin_map_service.proto file.

As is, you are leaking the client ID that you are explicitly creating and closing the connection from the channel pool instead.

![image](https://github.com/user-attachments/assets/e7473faf-b039-4eab-90d4-80159c77dd30)

2024-08-23 16:48 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
I don't know that you should need to change the file location because you add it to the palette, but we can tackle that issue in a future PR.

2024-08-23 16:49 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
This should not be calling `Destroy Client` as part of the implementation. That defeats the purpose of the client pool.

![image](https://github.com/user-attachments/assets/2b038a58-3250-4574-accb-4737698174e8)

2024-08-23 17:00 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
The `is registration successful?` output and logic doesn't seem necessary. If the registration is unsuccessful, that should be indicated by `error out`. As far as I can tell, the service will never return an empty string for the `pin_map_id` without also returning an error.

2024-08-23 17:02 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
If you plan to expose this publicly to users, then consider adding a VI description as well for context help purposes.

2024-08-23 17:05 UTC, jasonmreding requested changes
Since this introduces public APIs, waiting to see the next round of changes. You will eventually need to update the vipb as well, but I'm OK if you are planning to do that as part of a future PR.

2024-08-23 18:07 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
@jasonmreding With reference to [this](https://github.com/ni/measurement-plugin-labview/pull/571#discussion_r1716215002) comment in another PR for Discovery Destroy Client, I understand there is a bug in channel pool and there will a slow growing memory leak if we don't explicitly close the client. 

> Create a new public API that wraps the channel pool for the discovery service which clears out the underlying client session similar to what Kill Discovery Service.vi does in our test suite. At least that way, the channel pool isn't still holding onto a stale reference that is no longer valid.

So, In similar fashion for Pin Map client, I've created a public API that wraps channel the pool of pin map service to destroy the client. I've used this Destroy Client wherever we use Pin Map FGV to make sure we don't leave out any reference leaks from this VI as this a public API.

Please share your thoughts on this

2024-08-23 18:14 UTC, MounikaBattu17 commented
> You will eventually need to update the vipb as well

Could you please clarify why updating VIPB is necessary for these changes? Is it because the `Register PinMap.vi` going to get added to the palette?

2024-08-23 18:54 UTC, MounikaBattu17 commented on Source/Tests/Tests.Runtime/Measurement Server/Helpers/Kill Pin Map Service.vi
Updated. The Diff images are
![diagram-A-before-0](https://github.com/user-attachments/assets/2672cf3a-834f-4a2b-8159-154d4a633121)
![diagram-B-after-0](https://github.com/user-attachments/assets/16f48005-2c33-4206-b239-37b894056234)

2024-08-23 18:56 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
I've removed `is registration successful?` as `error out` is sufficient to tell whether registration is successful or not.

2024-08-23 18:58 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
Added.
![image](https://github.com/user-attachments/assets/030ae7eb-7fa8-4ba1-8270-e327cc6575b7)

2024-08-23 23:01 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
> I understand there is a bug in channel pool...

The bug is actually in grpc-labview. However, fixing the bug actually makes the use of the channel pool from within a measurement plugin useless. In other words, the channel pool only has efficacy across RPCs because of the bug.

In this case, the usage is coming from the client side and not the server side. That means the usage model is a bit different. In particular, I would expect typical client usage:
- Would not invoke VIs using call by reference which would create client connections. grpc-labview client connections that are created from a call by ref hierarchy will get cleaned up by LV when that call by ref hierarchy goes idle if the connection hasn't already been explicitly closed. However, because of the bug, the connection isn't actually cleaned up so there is a bit of a memory leak that can accrue. If you are using the channel pool, then the leak doesn't occur until the FGV for the channel pool goes idle. This is because the FGV will continue to use its existing connection reference, and because of the cleanup bug, the connection is actually still valid. Otherwise, the retry logic in the client wrappers would receive an error and immediately recreate a new connection each time. For measurement plugins, the FGV doesn't go idle until you stop the service, which is never for a deployed exe.
- Would involve VI hierarchies that start/stop frequently from interactive use. As opposed to a built exe for a measurement plugin which never stops once started.

So you have a few choices that I can see:
1. Never use the channel pool. Instead, users will have to manage the client ID if they want to reuse it across multiple operations. Alternatively, the API you offer could always create/close the connection each time. This might be reasonable for pin maps since I imagine the frequency of registration would be relatively low. 
2. Use the channel pool and live with the leaks with the expectation that the impact of the leaks will be minor until we can fix the bug and shore up functionality.
3. Use the channel pool and also expose the `Destroy Client` API publicly. Users would then be in charge of calling this API at the appropriate time if they are concerned about the memory leak. Basically the user would need to call this VI at the end of the scope in which they want to apply channel pooling.

Your current implementation makes use of the channel pool, but then immediately invalidates the channel pool which seems kind of pointless. I think it technically also creates race conditions where there could be other gRPC calls in flight on the channel, and then you end up tearing down the channel mid flight without the user really being aware that you are doing that. Also, the current implementation is also using the channel pool for the discovery client, and it isn't cleaning that up so it is being inconsistent. 

I was OK with explicitly calling `Destroy Client` for the generator use case because VIs used for tools menu plugins are already loaded into their own "sand boxed" context so you are completely isolated from other user code. That is not the case here. This code will go directly into the user's projects.

The other longer term option would be to just build channel pooling into grpc-labview at the C++ layer and get rid of all of this LV code which is attempting to do the same thing. Otherwise, the only real option I can think of as a fix is to augment the grpc-labview API to allow the caller to specify whether or not the connection should automatically be cleaned up. That would still leak a reference once per time the FGV goes idle if the caller didn't explicitly clean up the FGV before going idle.

2024-08-26 08:59 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Register Pin Map.vi
Thanks for the suggestion. Based on your feedback, I've removed `Destroy Client.vi` from Register Pin Map.vi and tests as it neglects the point of using channel pool. I went with third option and made the following changes:
1) Removed `Destroy Client.vi` from `Register Pin Map.vi`, not accounting for minor memory leaks.
2) Made `Destroy Client.vi` public so that users can use it to destroy clients whenever they intend to.

Please let me know if any additions are needed.

2024-08-26 09:02 UTC, MounikaBattu17 commented on Source/Tests/Tests.Runtime/Measurement Server/Pin Map/test_RegisterPinMap_RegisterPinMapFile_PinMapRegistered.vi
Used FGV to get the existing client ID and removed Destroy Client from the implementation.
![image](https://github.com/user-attachments/assets/c0ad25ac-0637-457a-8330-30f984216492)

2024-08-26 15:30 UTC, jasonmreding approved these changes

2024-08-28 11:57 UTC, Prem-MysteryPro commented on Source/Runtime/Clients/Pin Map V1/Recreate Client.vi
@MounikaBattu17 
Can we resize the front panel window to view all the controls completely? (ctrl + space, ctrl + f)
![image](https://github.com/user-attachments/assets/310e2510-5d10-487c-a066-2aac8ecf11cb)

2024-08-28 11:57 UTC, Prem-MysteryPro commented on Source/Runtime/Clients/Pin Map V1/Read Pin Map File Contents.vi
@MounikaBattu17 
Are there any ways to identify if the BOM character is present and remove it? Because now we are always removing the first 3 characters.
![image](https://github.com/user-attachments/assets/44656f1b-ff6e-4623-82ef-c2bd4c580a1f)

2024-08-28 15:52 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Pin Map Client FGV.vi
FGV stands for functional global variable. This design pattern only works if the VI is non-reentrant. It effectively provides a mutex around the execution of the VI/method which is needed for singleton like semantics.

2024-08-28 15:55 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Recreate Client.vi
If anything, use Ctrl + U to do a front panel cleanup similar to block diagram cleanup. Unlike block diagram cleanup, this pretty much works as desired 100% of the time and is better than trying to arrange things manually. The only exception would be for user interface VIs where users are expected to interact with the front panel and then run manually.

2024-08-28 16:36 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Read Pin Map File Contents.vi
I had missed this in my initial review. Is there any reason you are doing this? Out update pin map TestStand step type (or other pin map clients) don't try to remove the BOM and seem to work just fine. I guess maybe [File.ReadAllText](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.readalltext?view=net-8.0) is doing some of this for us in C#? You could also look at using `Read From XML File.vi` to see if automatically handles BOM for you.

![image](https://github.com/user-attachments/assets/4ec8fc21-bcf7-4422-9e4d-30101d9fffc0)

2024-08-28 16:55 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Create Client.vi
Updated the wire bends.

2024-08-28 16:56 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Recreate Client.vi
Thanks for the shortcuts. I've updated it accordingly.

2024-08-28 17:02 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Read Pin Map File Contents.vi
The pinmap file contents are read with additional BOM characters `ï»¿`, so I trimmed them from the final string. But now, I verified that even with BOM characters, pin map is registered successfully to the pin map service. Thus, I have removed the trimming.

2024-08-28 17:03 UTC, MounikaBattu17 commented on Source/Runtime/Clients/Pin Map V1/Pin Map Client FGV.vi
Thanks for the explanation!

2024-08-29 07:16 UTC, Prem-MysteryPro commented on Source/Runtime/Clients/Pin Map V1/Pin Map Client FGV.vi
@jasonmreding 
Thanks for the explanation.
I understand that FGV is always meant for singleton pattern. I have seen some FGV in our repository enabled as clone. For example, `NI Session Management V1 Client.lvlib:Session Client FGV.vi`
![image](https://github.com/user-attachments/assets/42b273bd-8c3f-499b-8cc6-e202a93be2ec)
Another example is `NI Discovery V1 Client.lvlib:gRPC Client Cache FGV Impl.vi`
![image](https://github.com/user-attachments/assets/4e62b8a6-9df3-4867-9c3a-fbc6badc5ef2)
I am thinking there is reason behind this (Channel pooling). Kindly educate us on this.

2024-08-29 10:18 UTC, Prem-MysteryPro commented on Source/Runtime/Clients/Pin Map V1/Read Pin Map File Contents.vi
Thanks for the suggestions, Jason. We tried `Read From XML File.vi`, I guess the XML schema of `Write To XML File.vi` is different from our pinmap XML so while using the `Read From XML" we are getting empty string as output so went ahead with normal read from text file. Removing BOM is not required and hence we removed that like Mounika mentioned in above comment.
![image](https://github.com/user-attachments/assets/76729e3d-e76c-4402-aa79-c04d3d70e154)

2024-08-29 18:54 UTC, jasonmreding commented on Source/Runtime/Clients/Pin Map V1/Pin Map Client FGV.vi
The `Session Client FGV.vi` is an oversight or bug of sorts. It should really be using non-reentrant execution. The idea is there is a FGV per service that we use (discovery, pin map, and session management), and this FGV serves as a cache for the client connection used to communicate with that service. However, the underlying implementation of the 3 FGVs is effectively the same. This is why `gRPC Client Cache FGV Impl.vi` exists and is marked as a reentrant VI with pre-allocated clones. This means a dedicated data space for the clone VI will get allocated up front at each call site. The call site in this case is the 3 FGVs which wrap it. Each of these is then marked as non-reentrant so there is only one call site for that service instance in memory. So the inner reentrant FGV is actually the thing with the shift register which caches the client connection and the outer non-reentrant FGV is what ensures there is a single instance for that service connection and that access is managed in a race free manner (i.e. a singleton).

Using a reentrant outer FGV with shared clones isn't necessarily functionally wrong. It just means if there are parallel calls to the FGV, a new clone and data space will get allocated on demand so the call can be executed in parallel with an ongoing call. The new clone will have a new allocation for the shift register which will be unitialized, which means it will create a new client connection for each clone. So in effect, you are creating N copies of the connection rather than reusing the existing connection.

This is all a bit hackish to get around the fact that grpc-labview doesn't expose a first class concept of a grpc channel like other languages do. If you read up about gRPC performance, it will say that channels should be long lived and that you should reuse them rather than constantly creating/destroying them. The initial establishment of the http connection is generally pretty expensive, and it usually consumes a TCP socket from the OS. Doing this too quickly can lead to socket exhaustion until enough time expires for the TCP connection to exit the time wait stage. So lacking an actual channel object, we are doing the next best thing which is to reuse the client itself for each service. This would be akin to reusing the client stub in other languages where the stub itself takes a grpc channel. In C# for instance, a common pattern is to create/destroy a new client stub for each RPC but to reuse the channel or http handler object. An alternative to implementing our own caching/pooling in G code would be to make the grpc-labview C++ just always use channel pooling for us as part of the implementation. However, that has its own trade offs when the user has no say in what is happening.

2024-08-30 04:28 UTC, Prem-MysteryPro commented on Source/Runtime/Clients/Pin Map V1/Pin Map Client FGV.vi
Thanks for the Detailed explanation, Jason.
In this case we will leave the pin map FGV as non-reentrant.

2024-08-30 04:29 UTC, Prem-MysteryPro approved these changes

2024-08-30 04:30 UTC, merged