[minor] update: generate error for case not found
ni/measurement-plugin-labview pull request #591
Opened 2024-09-16 14:47 UTC by varshini-senthil

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md). _(Required)_
- [ ]  Automatically post PR comments with images for G code changes? _(Recommended for small changes)_

### What does this Pull Request accomplish?

- Added custom error string in the global variable VI `Error Strings Global Internal.vi`, to indicate that no case exists for the given control name in `Update Control from Metadata.vi`.
    - This update is to alert the user about the change in control name in the Client template through error generation.

### Why should this Pull Request be merged?

- To update the global variable VI `Error Strings Global Internal.vi`.
- To update the `Update Control from Metadata.vi`, to generate error when no case found for the given control name.

### What testing has been done?

- Modified the measurement plug-in client template and tested error generation by creating a client.

2024-09-16 15:31 UTC, dixonjoel approved these changes

2024-09-16 21:52 UTC, jasonmreding commented on Source/Runtime/Measurements/Helpers/Error Strings Global Internal.vi
This error file is used by our runtime libraries to produce user facing error messages. I would prefer not to reference it from our generators as well. Instead, you should create a separate error file in that project if that is the route you want to go.

Some other thoughts:
- "No case found for the control name '%s'. Update case structure for the new control name and try again." reads more as a developer error and not as a user facing error. If this is something that could bubble up to the user, you might want to just say something like: "Internal error. No case found for the control name '%s'.".
- In past PRs, you made design trade offs which allowed you to run the generator from source without having to install any dependencies to the LV directory. Linking to the error VI from <vilib>is inconsistent with those decisions. Creating a new error file will resolve that.

2024-09-16 21:53 UTC, jasonmreding requested changes
Waiting to remove dependency on error file used by runtime libraries.

2024-09-17 08:28 UTC, varshini-senthil commented on Source/Runtime/Measurements/Helpers/Error Strings Global Internal.vi
I have reverted the changes to the global VI in the `Measurement Server.lvproj` and have added a new global VI `Generator Error Strings Global.vi` for the generators.

2024-09-17 16:03 UTC, jasonmreding commented on Source/Generator/_MeasurementClient Utility/Generator Error Strings Global.vi
If the goal is to share this error file across all of the generator libraries, I would probably move the file on disk from `_MeasurementClient Utility` to `_Generator Helpers`. If this is intended to be specific to just the client generator, then I would move the VI within the project items pane so it is under the Helpers folder of `MeasurementClient Editor.lvlib`.

2024-09-17 16:03 UTC, jasonmreding approved these changes

2024-09-19 08:47 UTC, merged