Added refresh support to measurement client
ni/measurement-plugin-labview pull request #615
Opened 2024-10-09 06:53 UTC by MounikaBattu17

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md). _(Required)_
- [ ]  Automatically post PR comments with images for G code changes? _(Recommended for small changes)_

### What does this Pull Request accomplish?
Added refresh support to the measurement client. This button updates the measurements list, resets the selection, and reverts any name changes in the `Available Measurements` list box.

### Why should this Pull Request be merged?
- Added a Refresh button in `Create Measurement Client.vi`.
- Updated the available services using `Enumerate Services.vi`.
- Utilized `List Available Measurements.vi` to refresh the list box with available services, resetting the selection and measurement service/client names.

### What testing has been done?
Manually tested the functionality.

2024-10-09 07:26 UTC, MounikaBattu17 commented
Diff changes:
![image](https://github.com/user-attachments/assets/b0d5e5f7-e89e-4741-bcc5-a5041c5b64b4)
![image](https://github.com/user-attachments/assets/c3854a1f-95e0-45cf-8fca-81aa24b0d815)

![Refresh support](https://github.com/user-attachments/assets/03fd7d34-7c30-4686-a9ae-9c9e4658f3df)

2024-10-09 09:28 UTC, Avinash2Suresh reviewed
When clicking the refresh button, it doesn’t provide the tactile feedback of a button click. Please consider updating the button to give users a sense of interaction, similar to how the Create Measurement Plug-in Client(s) button behaves.

2024-10-09 09:28 UTC, Avinash2Suresh commented
When clicking the refresh button, it doesn’t provide the tactile feedback of a button click. Please consider updating the button to give users a sense of interaction, similar to how the Create Measurement Plug-in Client(s) button behaves.

2024-10-09 09:29 UTC, Avinash2Suresh commented on Source/Generator/Create Measurement Client.vi
When clicking the refresh button, it doesn’t provide the tactile feedback of a button click. Please consider updating the button to give users a sense of interaction, similar to how the Create Measurement Plug-in Client(s) button behaves.

2024-10-09 09:31 UTC, Avinash2Suresh commented on Source/Generator/Create Measurement Client.vi
![image](https://github.com/user-attachments/assets/94d2c1a8-6f1b-48c6-8954-31868794dbbd)

I see a refresh lock and release here. I believe we should do the same for the Refresh value change event.

2024-10-09 09:33 UTC, Avinash2Suresh requested changes
I would like to see the updated changes.

2024-10-09 13:48 UTC, dixonjoel commented on Source/Generator/Create Measurement Client.vi
Agree with this. I can't vouch for this web page, but there are ways to put an image onto a button.
https://forums.ni.com/t5/LabVIEW/picture-on-button/td-p/852758

2024-10-09 18:19 UTC, MounikaBattu17 commented on Source/Generator/Create Measurement Client.vi
@dixonjoel 
Thank you for the resource! I created a custom refresh button based on the link. Could you please confirm if this button is okay?
![image](https://github.com/user-attachments/assets/48615239-d772-47e4-98ef-e6554bdd5665)
Post your confirmation, I'll update the code.

2024-10-09 18:37 UTC, MounikaBattu17 commented on Source/Generator/Create Measurement Client.vi
Here below is a small gif on the usage of button when running the client
![Refresh support](https://github.com/user-attachments/assets/5b30a61b-d447-4555-abf7-abfac57a5699)

2024-10-09 18:49 UTC, dixonjoel commented on Source/Generator/Create Measurement Client.vi
Yeah, looks fine to me.

2024-10-09 18:49 UTC, dixonjoel approved these changes

2024-10-09 18:51 UTC, MounikaBattu17 commented on Source/Generator/Create Measurement Client.vi
Sure Thank you. I have updated the code with this new refresh button.

2024-10-10 10:03 UTC, Avinash2Suresh approved these changes

2024-10-10 10:04 UTC, Avinash2Suresh commented
Please provide a tooltip for the Refresh button.

2024-10-10 10:05 UTC, Avinash2Suresh commented on Source/Generator/Create Measurement Client.vi
Consider adding a tooltip for the Refresh button.

2024-10-10 10:07 UTC, Avinash2Suresh commented on Source/Generator/Create Measurement Client.vi
I would recommend to create a typedef for the Refresh button.

2024-10-10 10:07 UTC, Prem-MysteryPro approved these changes
Can we add tool tip to the refresh button? I guess here the only reason could refreshing the measurement list but still. Let us have it.
If we customized the icon for this button, can we save it as typedef?

2024-10-10 10:25 UTC, MounikaBattu17 commented on Source/Generator/Create Measurement Client.vi
![image](https://github.com/user-attachments/assets/86774efa-b2ff-4d19-9b33-a3a0cc3143fa)

2024-10-10 10:25 UTC, MounikaBattu17 commented on Source/Generator/Create Measurement Client.vi
Created a typedef `Refresh Button.ctl`.

2024-10-10 11:10 UTC, merged